# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 594688613deb272e9e80d764a0206ca92783585c32d42f43c3d78a18750eb3aa34bb97248815e14536bdb2617498ddb1444d5e3e53e74adaf7c959d9e8c0bf41

test:
  secret_key_base: 91bb178fae23f36c766483336f6b622b4c0344212c29befeb0e7ed68522a9a5aee8577d83c22aad6bc803de0ee7275acc83a5ec97941441a90a2357c9d987bc8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
